### ISSUE TITLE
Test whether sealing can be overridden at class hierarchy depth > 1

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-define#48]
If I do

`var Foo = DefineMap.extend({ seal: true }, { ... })`

and later

`var Bar = Foo.extend({ seal: false }, { ... })`

Does that work?  Can I also then do:

`var Baz = Bar.extend({ seal: true }, { ... })` and so on?

**Comment by DesignByOnyx** [comment]
I have been testing this and extending sealed objects does indeed work, but I made two observations which may or may not be expected:

**Observation 1: sealed instances can be created with non-defined properties**

```js
var Map1 = DefineMap.extend("Map1", { seal: true }, {
    name: "string"
});

var map1 = new Map1({ name: "Justin", foo: "bar" });

map1.foo = "barbarbar";
map1.baz = "bazaar";
QUnit.equal(map1.foo, "barbarbar", "foo exists and is writable");
QUnit.equal(map1.baz, undefined, "baz property not created, as expected");
```

**Observation 2: extended objects are not getting the property definitions from parent**

```js
var Map1 = DefineMap.extend("Map1", { seal: true }, {
    name: "string"
});
var Map2 = Map1.extend("Map2", { seal: false }, {
    email: "string"
});
QUnit.ok(Object.getOwnPropertyDescriptor(Map1.prototype, "name"), "Map1 has 'name' descriptor"); // passes
QUnit.ok(Object.getOwnPropertyDescriptor(Map2.prototype, "name"), "Map2 has 'name' descriptor"); // fails - undefined
QUnit.ok(Object.getOwnPropertyDescriptor(Map2.prototype, "email"), "Map2 has 'email' descriptor"); // passes
```

**Comment by DesignByOnyx** [comment]
My second observation is not relevant because `Map2` does not have its **own** property descriptor for `name` - but the prototype chain still contains the definition. Any getters or setters and other propDefinitions are inherited as you would expect.

My first observation is still a little troubling. There is currently a test for initializing undefined properties:

https://github.com/canjs/can-define/blob/master/map/map-test.js#L149

... but the test only tests the case where `{seal: false}`. It doesn't matter what the value of "seal" is - undefined properties are *always* initialized. This may be a bug.
