### ISSUE TITLE
Add a delete method for removing properties.

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-define#94]
Not sure what the API would be.  Open to suggestions.

**Comment by justinbmeyer** [comment]
define.delete("key");

However `delete` doesn't really make sense for seal-ed objects.  Why do you need a `delete`?

**Comment by marshallswain** [comment]
Dunno.  It has been too long.

**Comment by bmomberger-bitovi** [comment]
I looked into the possibility of removing properties from a DefineMap recently, and I didn't like what I saw.  A couple notes:

* There is no way to remove property definitions from an object once set.
* once a property definition is set on an object, `in` operators on that property name are always true, even if no value has been set with assignment.
* A property can be deleted from an object if the property wasn't defined directly on the object (in other words, up the prototype chain), so:
  * `new DefineMap({ a: 'b' })` => not deletable
  * `x = new DefineMap(); x.set('a', 'b');` => not deletable
  * `x = new (DefineMap.extend({ a: {} }))(); x.a = 'b'` => deletable, because property definitions are on a prototype.  `in` is still true here, but `x.hasOwnProperty('a')` will be false after deletion.

We might want to create ad hoc prototype objects for DefineMap instances, and strongly encourage users to do the same when using `define()` on other objects.
